/**
 * ==============================================================================
 * GURUPRO AI: PRESENTATION TEACHER REVIEW CONTRACT (PPT-1E)
 * ==============================================================================
 *
 * Defines canonical data contracts, Zod schemas, state transition matrices,
 * and input specifications for teacher-driven presentation review & approval.
 *
 * Invariants:
 * 1. Semantic Separation: reviewStatus (generated, in_review, approved, rejected, superseded)
 *    is STRICTLY distinct from artifact generation status and AI content status.
 * 2. Version-Bound Approval: Teacher approval is strictly bound to an exact contentResultId
 *    and approvedVersion. Any modification to content or outline renders previous approval superseded.
 * 3. Human-Only Decision: Review decisions and notes are 100% authored by teachers.
 *    No automated AI approval is permitted.
 * 4. Multi-Tenant RBAC: Only the owning teacher can review and approve a presentation.
 * 5. Illustration Approval Invariant: Presentations referencing illustrations cannot be
 *    approved unless all referenced illustrations have review_status === "approved_for_use".
 */

import { z } from "zod";
import { AI_ERROR_CODES, AiServiceError } from "./error-taxonomy";
import type { PresentationContentPackage } from "./presentation-generation-contract";
import type { ResolvedSlideIllustration } from "./presentation-illustration-resolver";

// ==============================================================================
// 1. REVIEW STATUS DOMAIN & ENUM
// ==============================================================================

export const PresentationReviewStatusSchema = z.enum([
  "generated",   // Content generated by PPT-1B, waiting for teacher to start review
  "in_review",   // Teacher is actively inspecting slides and verifying content
  "approved",    // Teacher explicitly approved this exact version for pedagogical use
  "rejected",    // Teacher rejected this version with feedback notes
  "superseded",  // Previous version replaced by a newer revision or regenerated content
]);
export type PresentationReviewStatus = z.infer<typeof PresentationReviewStatusSchema>;

// ==============================================================================
// 2. CANONICAL PRESENTATION REVIEW ENTITY SCHEMA
// ==============================================================================

export const PresentationReviewSchema = z.object({
  id: z.string().min(1, "ID review wajib ada."),
  presentationId: z.string().min(1, "Presentation ID wajib ada."),
  contentResultId: z.string().min(1, "Content Result ID wajib ada."),
  generationPlanId: z.string().min(1, "Generation Plan ID wajib ada."),
  moduleId: z.string().min(1, "Module ID wajib ada."),
  approvedVersion: z.number().int().min(1, "Versi rencana wajib >= 1."),
  reviewStatus: PresentationReviewStatusSchema,
  teacherNotes: z.string().max(3000, "Catatan guru maksimal 3000 karakter.").nullable().optional(),
  validationSummary: z.record(z.any()).default({}),
  reviewedBy: z.string().min(1, "ID guru peninjau wajib ada."),
  reviewedAt: z.string().nullable().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type PresentationReview = z.infer<typeof PresentationReviewSchema>;

// ==============================================================================
// 3. REVIEW STATE MACHINE & TRANSITIONS
// ==============================================================================

const ALLOWED_PRESENTATION_REVIEW_TRANSITIONS: Record<
  PresentationReviewStatus,
  PresentationReviewStatus[]
> = {
  generated: ["in_review", "approved", "rejected", "superseded"],
  in_review: ["approved", "rejected", "superseded"],
  approved: ["in_review", "superseded"],
  rejected: ["in_review", "superseded"],
  superseded: [], // Terminal state for historical snapshot
};

export function validatePresentationReviewTransition(
  currentStatus: PresentationReviewStatus,
  targetStatus: PresentationReviewStatus
): boolean {
  if (currentStatus === targetStatus) return true;
  const allowed = ALLOWED_PRESENTATION_REVIEW_TRANSITIONS[currentStatus] || [];
  return allowed.includes(targetStatus);
}

export function assertValidPresentationReviewTransition(
  currentStatus: PresentationReviewStatus,
  targetStatus: PresentationReviewStatus
): void {
  if (!validatePresentationReviewTransition(currentStatus, targetStatus)) {
    throw new AiServiceError(
      AI_ERROR_CODES.PRESENTATION_REVIEW_INVALID_TRANSITION,
      `Transisi status review presentasi dari '${currentStatus}' ke '${targetStatus}' tidak diizinkan.`
    );
  }
}

// ==============================================================================
// 4. SERVER FUNCTION INPUT SCHEMAS
// ==============================================================================

export const StartPresentationReviewInputSchema = z.object({
  contentResultId: z.string().min(1, "ID hasil generasi konten presentasi wajib diisi."),
});
export type StartPresentationReviewInput = z.infer<typeof StartPresentationReviewInputSchema>;

export const ApprovePresentationInputSchema = z.object({
  contentResultId: z.string().min(1, "ID hasil generasi konten presentasi wajib diisi."),
  teacherNotes: z.string().max(3000).nullable().optional(),
  expectedVersion: z.number().int().optional(),
});
export type ApprovePresentationInput = z.infer<typeof ApprovePresentationInputSchema>;

export const RejectPresentationInputSchema = z.object({
  contentResultId: z.string().min(1, "ID hasil generasi konten presentasi wajib diisi."),
  teacherNotes: z
    .string()
    .trim()
    .min(1, "Harap berikan catatan alasan penolakan presentasi untuk panduan perbaikan.")
    .max(3000),
  expectedVersion: z.number().int().optional(),
});
export type RejectPresentationInput = z.infer<typeof RejectPresentationInputSchema>;

export const UpdatePresentationReviewNotesInputSchema = z.object({
  contentResultId: z.string().min(1, "ID hasil generasi konten presentasi wajib diisi."),
  teacherNotes: z.string().max(3000).nullable().optional(),
});
export type UpdatePresentationReviewNotesInput = z.infer<
  typeof UpdatePresentationReviewNotesInputSchema
>;

export const GetPresentationReviewInputSchema = z.object({
  contentResultId: z.string().min(1, "ID hasil generasi konten presentasi wajib diisi."),
});
export type GetPresentationReviewInput = z.infer<typeof GetPresentationReviewInputSchema>;

export const ListPresentationReviewsInputSchema = z.object({
  moduleId: z.string().min(1, "ID modul ajar wajib diisi."),
  generationPlanId: z.string().optional(),
});
export type ListPresentationReviewsInput = z.infer<typeof ListPresentationReviewsInputSchema>;

// ==============================================================================
// 5. ILLUSTRATION APPROVAL PRECONDITION VALIDATOR
// ==============================================================================

export interface PresentationIllustrationAuditItem {
  slideId: string;
  slideOrder: number;
  assetId: string;
  isApproved: boolean;
  reviewStatus?: string;
  issue?: string;
}

export interface PresentationIllustrationAuditResult {
  valid: boolean;
  totalReferenced: number;
  approvedCount: number;
  unapprovedCount: number;
  items: PresentationIllustrationAuditItem[];
}

/**
 * Audits all illustration references across slides in a presentation content package.
 * Enforces that every referenced illustration is actively approved for use.
 */
export function auditPresentationIllustrations(
  contentPackage: PresentationContentPackage,
  resolvedIllustrations?: Map<string, ResolvedSlideIllustration>
): PresentationIllustrationAuditResult {
  const items: PresentationIllustrationAuditItem[] = [];
  let unapprovedCount = 0;
  let approvedCount = 0;

  for (const slide of contentPackage.slides) {
    const ref = slide.illustrationReference;
    if (!ref || !ref.assetId) continue;

    const resolved = resolvedIllustrations?.get(slide.slideId);
    if (resolved) {
      approvedCount++;
      items.push({
        slideId: slide.slideId,
        slideOrder: slide.order,
        assetId: ref.assetId,
        isApproved: true,
        reviewStatus: "approved_for_use",
      });
    } else {
      unapprovedCount++;
      const status = ref.reviewStatus || "unreviewed";
      items.push({
        slideId: slide.slideId,
        slideOrder: slide.order,
        assetId: ref.assetId,
        isApproved: false,
        reviewStatus: status,
        issue: `Ilustrasi belum disetujui (status: ${status}).`,
      });
    }
  }

  return {
    valid: unapprovedCount === 0,
    totalReferenced: items.length,
    approvedCount,
    unapprovedCount,
    items,
  };
}
