/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArsipRouteImport } from './routes/arsip'
import { Route as ModulAjarRouteImport } from './routes/modul-ajar'
import { Route as PenilaianRouteImport } from './routes/penilaian'
import { Route as PenugasanRouteImport } from './routes/penugasan'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SoalRouteImport } from './routes/soal'
import { Route as VerifikasiRouteImport } from './routes/verifikasi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipRoute = ArsipRouteImport.update({
  id: '/arsip',
  path: '/arsip',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulAjarRoute = ModulAjarRouteImport.update({
  id: '/modul-ajar',
  path: '/modul-ajar',
  getParentRoute: () => rootRouteImport,
} as any)
const PenilaianRoute = PenilaianRouteImport.update({
  id: '/penilaian',
  path: '/penilaian',
  getParentRoute: () => rootRouteImport,
} as any)
const PenugasanRoute = PenugasanRouteImport.update({
  id: '/penugasan',
  path: '/penugasan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SoalRoute = SoalRouteImport.update({
  id: '/soal',
  path: '/soal',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifikasiRoute = VerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arsip': typeof ArsipRoute
  '/modul-ajar': typeof ModulAjarRoute
  '/penilaian': typeof PenilaianRoute
  '/penugasan': typeof PenugasanRoute
  '/profil': typeof ProfilRoute
  '/soal': typeof SoalRoute
  '/verifikasi': typeof VerifikasiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arsip': typeof ArsipRoute
  '/modul-ajar': typeof ModulAjarRoute
  '/penilaian': typeof PenilaianRoute
  '/penugasan': typeof PenugasanRoute
  '/profil': typeof ProfilRoute
  '/soal': typeof SoalRoute
  '/verifikasi': typeof VerifikasiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arsip': typeof ArsipRoute
  '/modul-ajar': typeof ModulAjarRoute
  '/penilaian': typeof PenilaianRoute
  '/penugasan': typeof PenugasanRoute
  '/profil': typeof ProfilRoute
  '/soal': typeof SoalRoute
  '/verifikasi': typeof VerifikasiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arsip'
    | '/modul-ajar'
    | '/penilaian'
    | '/penugasan'
    | '/profil'
    | '/soal'
    | '/verifikasi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arsip'
    | '/modul-ajar'
    | '/penilaian'
    | '/penugasan'
    | '/profil'
    | '/soal'
    | '/verifikasi'
  id:
    | '__root__'
    | '/'
    | '/arsip'
    | '/modul-ajar'
    | '/penilaian'
    | '/penugasan'
    | '/profil'
    | '/soal'
    | '/verifikasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArsipRoute: typeof ArsipRoute
  ModulAjarRoute: typeof ModulAjarRoute
  PenilaianRoute: typeof PenilaianRoute
  PenugasanRoute: typeof PenugasanRoute
  ProfilRoute: typeof ProfilRoute
  SoalRoute: typeof SoalRoute
  VerifikasiRoute: typeof VerifikasiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip': {
      id: '/arsip'
      path: '/arsip'
      fullPath: '/arsip'
      preLoaderRoute: typeof ArsipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul-ajar': {
      id: '/modul-ajar'
      path: '/modul-ajar'
      fullPath: '/modul-ajar'
      preLoaderRoute: typeof ModulAjarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penilaian': {
      id: '/penilaian'
      path: '/penilaian'
      fullPath: '/penilaian'
      preLoaderRoute: typeof PenilaianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penugasan': {
      id: '/penugasan'
      path: '/penugasan'
      fullPath: '/penugasan'
      preLoaderRoute: typeof PenugasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soal': {
      id: '/soal'
      path: '/soal'
      fullPath: '/soal'
      preLoaderRoute: typeof SoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifikasi': {
      id: '/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof VerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArsipRoute: ArsipRoute,
  ModulAjarRoute: ModulAjarRoute,
  PenilaianRoute: PenilaianRoute,
  PenugasanRoute: PenugasanRoute,
  ProfilRoute: ProfilRoute,
  SoalRoute: SoalRoute,
  VerifikasiRoute: VerifikasiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
