/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JurnalIndexRouteImport } from './routes/jurnal/index'
import { Route as JurnalCreateRouteImport } from './routes/jurnal/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JurnalIndexRoute = JurnalIndexRouteImport.update({
  id: '/jurnal/',
  path: '/jurnal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JurnalCreateRoute = JurnalCreateRouteImport.update({
  id: '/jurnal/create',
  path: '/jurnal/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jurnal/create': typeof JurnalCreateRoute
  '/jurnal/': typeof JurnalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jurnal/create': typeof JurnalCreateRoute
  '/jurnal': typeof JurnalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jurnal/create': typeof JurnalCreateRoute
  '/jurnal/': typeof JurnalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jurnal/create' | '/jurnal/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jurnal/create' | '/jurnal'
  id: '__root__' | '/' | '/jurnal/create' | '/jurnal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JurnalCreateRoute: typeof JurnalCreateRoute
  JurnalIndexRoute: typeof JurnalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurnal/': {
      id: '/jurnal/'
      path: '/jurnal'
      fullPath: '/jurnal/'
      preLoaderRoute: typeof JurnalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurnal/create': {
      id: '/jurnal/create'
      path: '/jurnal/create'
      fullPath: '/jurnal/create'
      preLoaderRoute: typeof JurnalCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JurnalCreateRoute: JurnalCreateRoute,
  JurnalIndexRoute: JurnalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
