// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  fetchAuthUser,
  isJwtExpired,
  readJwtPayload,
  resolveRequestAccessToken,
  sessionExpiredError,
} from "./auth-token";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAuthClient(supabaseUrl: string, supabaseKey: string) {
  return createClient<Database>(supabaseUrl, supabaseKey, {
    global: {
      fetch: createSupabaseFetch(supabaseKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

function createUserScopedSupabaseClient(
  supabaseUrl: string,
  supabaseKey: string,
  accessToken: string,
) {
  return createClient<Database>(supabaseUrl, supabaseKey, {
    accessToken: async () => accessToken,
    global: {
      fetch: createSupabaseFetch(supabaseKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

export const CANONICAL_SUPABASE_PROJECT_ID = "dxzzpsrgbiummjplggyo";
export const CANONICAL_SUPABASE_URL = "https://dxzzpsrgbiummjplggyo.supabase.co";
export const CANONICAL_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_T_KM74qD7YgJYa4Om9jnww_HTzRSjs-";
const STALE_PROJECT_SUBSTRINGS = ["qfmrappbqslazyxgvbpg", "_KQPLPG8a6MMUy6Yh91XHA_6CB7fP8p"];

export function isApiKeyError(err: unknown): boolean {
  if (!err) return false;
  const msg = (
    typeof err === "object" && err !== null && "message" in err
      ? String((err as any).message)
      : String(err)
  ).toLowerCase();
  return (
    msg.includes("invalid api key") ||
    msg.includes("no api key found") ||
    msg.includes("apikey") ||
    msg.includes("pgrst301") ||
    msg.includes("jwt claim and api key mismatch")
  );
}

export function sanitizeEnvValue(val?: string | null): string {
  if (!val || typeof val !== "string") return "";
  let cleaned = val.trim();
  if ((cleaned.startsWith('"') && cleaned.endsWith('"')) || (cleaned.startsWith("'") && cleaned.endsWith("'"))) {
    cleaned = cleaned.slice(1, -1).trim();
  }
  return cleaned;
}

export function resolveSupabaseUrl(): string {
  const candidates = [
    process.env["SUPABASE_URL"],
    process.env["VITE_SUPABASE_URL"],
    process.env["NEXT_PUBLIC_SUPABASE_URL"],
    typeof import.meta !== "undefined" ? import.meta.env?.["VITE_SUPABASE_URL"] : undefined,
    typeof import.meta !== "undefined" ? import.meta.env?.["NEXT_PUBLIC_SUPABASE_URL"] : undefined,
  ];

  for (const raw of candidates) {
    const val = sanitizeEnvValue(raw).replace(/\/+$/, "");
    if (!val) continue;
    if (STALE_PROJECT_SUBSTRINGS.some((stale) => val.includes(stale))) {
      console.warn(`[Supabase] Ignored stale project URL (${val}), using canonical project URL`);
      continue;
    }
    return val;
  }

  return CANONICAL_SUPABASE_URL;
}

export function resolveSupabasePublishableKey(): string {
  const targetUrl = resolveSupabaseUrl();
  const isCanonicalTarget = targetUrl.includes(CANONICAL_SUPABASE_PROJECT_ID);

  const candidates = [
    process.env["SUPABASE_PUBLISHABLE_KEY"],
    process.env["SUPABASE_ANON_KEY"],
    process.env["VITE_SUPABASE_PUBLISHABLE_KEY"],
    process.env["VITE_SUPABASE_ANON_KEY"],
    process.env["NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"],
    process.env["NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    typeof import.meta !== "undefined" ? import.meta.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"] : undefined,
    typeof import.meta !== "undefined" ? import.meta.env?.["VITE_SUPABASE_ANON_KEY"] : undefined,
  ];

  for (const raw of candidates) {
    const val = sanitizeEnvValue(raw);
    if (!val) continue;
    if (STALE_PROJECT_SUBSTRINGS.some((stale) => val.includes(stale))) {
      console.warn("[Supabase] Ignored stale project publishable key, using canonical key");
      continue;
    }
    if (isCanonicalTarget && val.startsWith("sb_publishable_") && val !== CANONICAL_SUPABASE_PUBLISHABLE_KEY) {
      console.warn("[Supabase] Ignored mismatched publishable key for canonical project, using canonical key");
      continue;
    }
    return val;
  }

  return CANONICAL_SUPABASE_PUBLISHABLE_KEY;
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = resolveSupabaseUrl();
    const SUPABASE_PUBLISHABLE_KEY = resolveSupabasePublishableKey();

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please configure your .env file.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const token = resolveRequestAccessToken(request.headers);

    if (!token) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (isJwtExpired(token, 0)) {
      throw sessionExpiredError();
    }

    const authClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    let userId: string | null = null;
    let claims: any = null;

    try {
      const { data, error } = await authClient.auth.getClaims(token);
      if (!error && data?.claims?.sub) {
        userId = data.claims.sub;
        claims = data.claims;
      } else if (error) {
        console.warn("[AuthMiddleware] getClaims returned error, falling back to getUser:", error.message);
      }
    } catch (claimsErr: any) {
      console.warn("[AuthMiddleware] getClaims threw exception, falling back to getUser:", claimsErr?.message);
    }

    if (!userId) {
      try {
        const { data: userData, error: userError } = await authClient.auth.getUser(token);
        if (!userError && userData?.user?.id) {
          userId = userData.user.id;
          claims = userData.user;
        } else if (userError) {
          console.warn("[AuthMiddleware] getUser failed, falling back to Auth API:", userError.message);
        }
      } catch (userErr: any) {
        console.warn("[AuthMiddleware] getUser threw exception, falling back to Auth API:", userErr?.message);
      }
    }

    if (!userId) {
      try {
        const user = await fetchAuthUser(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, token);
        userId = user.id;
        claims = user;
      } catch (apiErr: any) {
        throw sessionExpiredError();
      }
    }

    if (!userId) {
      throw sessionExpiredError();
    }

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      accessToken: async () => token,
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    return next({
      context: {
        supabase,
        userId,
        claims,
        token,
        supabaseUrl: SUPABASE_URL,
        supabaseKey: SUPABASE_PUBLISHABLE_KEY,
      },
    });
  },
);

async function fetchVerifiedProfile(
  supabase: any,
  userId: string,
  token?: string | null,
): Promise<{ profile: any; dbError: any }> {
  let profile: any = null;
  let dbError: any = null;

  try {
    const { data, error } = await supabase
      .from("profiles")
      .select("role, status_verifikasi")
      .eq("id", userId)
      .maybeSingle();

    if (error) {
      dbError = error;
      console.warn("[AuthMiddleware] Database query on profiles returned error:", error.message);
    } else if (data) {
      profile = data;
    }
  } catch (err: any) {
    dbError = err;
    console.warn("[AuthMiddleware] Exception querying profiles:", err?.message);
  }

  // Fallback 1: If profile query failed with API key error, retry with verified canonical Supabase client
  if (!profile && dbError && isApiKeyError(dbError) && token) {
    console.warn(
      "[AuthMiddleware] Retrying profiles query with verified canonical Supabase client due to API key error:",
      dbError.message,
    );
    try {
      const canonicalClient = createUserScopedSupabaseClient(
        CANONICAL_SUPABASE_URL,
        CANONICAL_SUPABASE_PUBLISHABLE_KEY,
        token,
      );
      const { data: retryData, error: retryErr } = await canonicalClient
        .from("profiles")
        .select("role, status_verifikasi")
        .eq("id", userId)
        .maybeSingle();

      if (!retryErr && retryData) {
        profile = retryData;
        dbError = null;
        console.log("[AuthMiddleware] Successfully loaded profile via canonical Supabase client retry.");
      } else if (retryErr) {
        console.warn("[AuthMiddleware] Canonical retry returned error:", retryErr.message);
      }
    } catch (retryEx: any) {
      console.warn("[AuthMiddleware] Canonical retry exception:", retryEx?.message);
    }
  }

  // Fallback 2: Admin client fallback if service role key exists
  if (!profile && dbError) {
    if (process.env["SUPABASE_SERVICE_ROLE_KEY"] || process.env["SERVICE_ROLE_KEY"]) {
      try {
        const { supabaseAdmin } = await import("./client.server");
        const { data: adminProfile, error: adminErr } = await supabaseAdmin
          .from("profiles")
          .select("role, status_verifikasi")
          .eq("id", userId)
          .maybeSingle();

        if (!adminErr && adminProfile) {
          profile = adminProfile;
          dbError = null;
        }
      } catch {
        // Keep original dbError if admin fallback fails
      }
    }
  }

  return { profile, dbError };
}

export const requireGuruAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const supabase = (context as any).supabase;
    const userId = (context as any).userId;
    const token = (context as any).token;

    const { profile, dbError } = await fetchVerifiedProfile(supabase, userId, token);

    if (!profile) {
      if (dbError) {
        console.error("[AuthMiddleware] Failed to query profiles:", dbError.message);
        throw new Error(`Forbidden: Gagal memuat profil basis data (${dbError.message})`);
      }
      console.warn("[AuthMiddleware] Profile not found in database for user:", userId);
      throw new Error("Forbidden: Profil pengguna tidak ditemukan.");
    }

    const userRole = String(profile.role || "").toLowerCase().trim();
    if (userRole !== "guru" && userRole !== "admin") {
      throw new Error("Forbidden: Operasi ini hanya diizinkan untuk peran Guru.");
    }

    if (userRole === "guru") {
      const status = String(profile.status_verifikasi || "").toLowerCase().trim();
      if (status === "menunggu") {
        throw new Error("Forbidden: Akun guru Anda sedang menunggu verifikasi.");
      }
      if (status === "ditolak" || status === "nonaktif") {
        throw new Error("Forbidden: Akun guru Anda ditolak atau belum aktif.");
      }
    }

    return next({
      context: {
        ...context,
        profile,
      },
    });
  });

export const requireTeacherAiAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const supabase = (context as any).supabase;
    const userId = (context as any).userId;
    const token = (context as any).token;

    const { profile, dbError } = await fetchVerifiedProfile(supabase, userId, token);

    if (!profile) {
      if (dbError) {
        throw new Error(`Forbidden: Gagal memuat profil basis data (${dbError.message})`);
      }
      throw new Error("Forbidden: Profil pengguna tidak ditemukan.");
    }

    const userRole = String(profile.role || "").toLowerCase().trim();
    // Strict Teacher AI Boundary: Only verified guru accounts are permitted
    if (userRole !== "guru") {
      throw new Error("Forbidden: Operasi AI hanya diizinkan untuk peran Guru.");
    }

    const status = String(profile.status_verifikasi || "").toLowerCase().trim();
    if (status === "menunggu") {
      throw new Error("Forbidden: Akun guru Anda sedang menunggu verifikasi.");
    }
    if (status === "ditolak" || status === "nonaktif") {
      throw new Error("Forbidden: Akun guru Anda ditolak atau belum aktif.");
    }

    return next({
      context: {
        ...context,
        profile,
      },
    });
  });

