// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  fetchAuthUser,
  isJwtExpired,
  readJwtPayload,
  resolveRequestAccessToken,
  sessionExpiredError,
} from "./auth-token";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAuthClient(supabaseUrl: string, supabaseKey: string) {
  return createClient<Database>(supabaseUrl, supabaseKey, {
    global: {
      fetch: createSupabaseFetch(supabaseKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

function createUserScopedSupabaseClient(
  supabaseUrl: string,
  supabaseKey: string,
  accessToken: string,
) {
  return createClient<Database>(supabaseUrl, supabaseKey, {
    accessToken: async () => accessToken,
    global: {
      fetch: createSupabaseFetch(supabaseKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL =
      process.env["SUPABASE_URL"] ||
      process.env["VITE_SUPABASE_URL"] ||
      (typeof import.meta !== "undefined" ? import.meta.env?.["VITE_SUPABASE_URL"] : undefined) ||
      "https://dxzzpsrgbiummjplggyo.supabase.co";

    const SUPABASE_PUBLISHABLE_KEY =
      process.env["SUPABASE_PUBLISHABLE_KEY"] ||
      process.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
      (typeof import.meta !== "undefined" ? import.meta.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"] : undefined) ||
      "sb_publishable_T_KM74qD7YgJYa4Om9jnww_HTzRSjs-";

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please configure your .env file.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const token = resolveRequestAccessToken(request.headers);

    if (!token) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (isJwtExpired(token, 0)) {
      throw sessionExpiredError();
    }

    const authClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    let userId: string | null = null;
    let claims: any = null;

    try {
      const { data, error } = await authClient.auth.getClaims(token);
      if (!error && data?.claims?.sub) {
        userId = data.claims.sub;
        claims = data.claims;
      } else if (error) {
        console.warn("[AuthMiddleware] getClaims returned error, falling back to getUser:", error.message);
      }
    } catch (claimsErr: any) {
      console.warn("[AuthMiddleware] getClaims threw exception, falling back to getUser:", claimsErr?.message);
    }

    if (!userId) {
      try {
        const { data: userData, error: userError } = await authClient.auth.getUser(token);
        if (!userError && userData?.user?.id) {
          userId = userData.user.id;
          claims = userData.user;
        } else if (userError) {
          console.warn("[AuthMiddleware] getUser failed, falling back to Auth API:", userError.message);
        }
      } catch (userErr: any) {
        console.warn("[AuthMiddleware] getUser threw exception, falling back to Auth API:", userErr?.message);
      }
    }

    if (!userId) {
      try {
        const user = await fetchAuthUser(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, token);
        userId = user.id;
        claims = user;
      } catch (apiErr: any) {
        const detail = String(apiErr?.message || "");
        console.warn("[AuthMiddleware] fetchAuthUser failed:", detail);
        if (/expired|invalid jwt|jwt expired|bad_jwt/i.test(detail)) {
          throw sessionExpiredError();
        }

        // If Auth gateway has a network/connectivity issue, fall back to unexpired JWT payload
        const payload = readJwtPayload(token);
        if (
          payload &&
          typeof payload.sub === "string" &&
          payload.sub.length > 0 &&
          !isJwtExpired(token, 0)
        ) {
          console.warn("[AuthMiddleware] Auth API network issue; falling back to JWT payload sub:", payload.sub);
          userId = payload.sub;
          claims = payload;
        } else {
          throw new Error("Unauthorized: Invalid token");
        }
      }
    }

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      accessToken: async () => token,
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    });
  },
);

export const requireGuruAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const supabase = (context as any).supabase;
    const userId = (context as any).userId;
    const claims = (context as any).claims;

    let profile: any = null;
    let dbError: any = null;

    try {
      // Validasi peran guru / admin di database server
      const { data, error } = await supabase
        .from("profiles")
        .select("role, status_verifikasi")
        .eq("id", userId)
        .maybeSingle();

      if (error) {
        dbError = error;
        console.warn("[AuthMiddleware] Database query on profiles returned error:", error.message);
      } else if (data) {
        profile = data;
      }
    } catch (err: any) {
      dbError = err;
      console.warn("[AuthMiddleware] Exception querying profiles:", err?.message);
    }

    // Fail-safe role fallback: jika profil DB gagal diakses karena RLS / koneksi,
    // gunakan klaim autentikasi Supabase yang sudah diverifikasi oleh requireSupabaseAuth
    if (!profile) {
      const claimRole = String(
        claims?.user_metadata?.role ||
        claims?.app_metadata?.role ||
        claims?.role ||
        ""
      ).toLowerCase().trim();

      if (claimRole === "guru" || claimRole === "admin") {
        console.info(`[AuthMiddleware] Using verified auth token metadata role (${claimRole}) for user:`, userId);
        profile = {
          role: claimRole,
          status_verifikasi: "terverifikasi",
        };
      }
    }

    if (!profile) {
      if (dbError) {
        console.error("[AuthMiddleware] Failed to query profiles and no claim role:", dbError.message);
        throw new Error(`Forbidden: Gagal memuat profil basis data (${dbError.message})`);
      }
      console.warn("[AuthMiddleware] Profile not found in database and claims for user:", userId);
      throw new Error("Forbidden: Profil pengguna tidak ditemukan.");
    }

    const userRole = String(profile.role || "").toLowerCase().trim();
    if (userRole !== "guru" && userRole !== "admin") {
      throw new Error("Forbidden: Operasi ini hanya diizinkan untuk peran Guru.");
    }

    if (userRole === "guru" && String(profile.status_verifikasi || "").toLowerCase().trim() === "ditolak") {
      throw new Error("Forbidden: Akun guru Anda ditolak atau belum aktif.");
    }

    return next({
      context: {
        ...context,
        profile,
      },
    });
  });