// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAuthClient(supabaseUrl: string, supabaseKey: string) {
  return createClient<Database>(supabaseUrl, supabaseKey, {
    global: {
      fetch: createSupabaseFetch(supabaseKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

function createUserScopedSupabaseClient(
  supabaseUrl: string,
  supabaseKey: string,
  accessToken: string,
) {
  return createClient<Database>(supabaseUrl, supabaseKey, {
    accessToken: async () => accessToken,
    global: {
      fetch: createSupabaseFetch(supabaseKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please configure your .env file.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const authClient = createSupabaseAuthClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

    const { data, error } = await authClient.auth.getUser(token);
    if (error || !data?.user) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.user.id) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    const supabase = createUserScopedSupabaseClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, token);

    return next({
      context: {
        supabase,
        userId: data.user.id,
        user: data.user,
      },
    });
  },
);

export const requireGuruAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const supabase = (context as any).supabase;
    const userId = (context as any).userId;

    // Validasi peran guru / admin di database server
    const { data: profile, error } = await supabase
      .from("profiles")
      .select("role, status_verifikasi")
      .eq("id", userId)
      .maybeSingle();

    if (error) {
      console.error("[Supabase] Failed to load profile for authenticated request:", error.message);
      throw new Error("Unauthorized: Gagal memuat profil pengguna.");
    }

    if (!profile) {
      throw new Error("Unauthorized: Profil pengguna tidak ditemukan.");
    }

    if (profile.role !== "guru" && profile.role !== "admin") {
      throw new Error("Forbidden: Operasi ini hanya diizinkan untuk peran Guru.");
    }

    if (profile.role === "guru" && profile.status_verifikasi === "ditolak") {
      throw new Error("Forbidden: Akun guru Anda ditolak atau belum aktif.");
    }

    return next({
      context: {
        ...context,
        profile,
      },
    });
  });
