// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";
import {
  ACCESS_TOKEN_HEADER,
  isJwtExpired,
  isSessionExpiring,
} from "./auth-token";

function getLocalStoredTokens(): { accessToken: string | null; refreshToken: string | null } {
  if (typeof window === "undefined" || !window.localStorage) {
    return { accessToken: null, refreshToken: null };
  }
  try {
    for (let i = 0; i < window.localStorage.length; i++) {
      const key = window.localStorage.key(i);
      if (key && key.startsWith("sb-") && key.endsWith("-auth-token")) {
        const val = window.localStorage.getItem(key);
        if (val) {
          const parsed = JSON.parse(val);
          return {
            accessToken: parsed?.access_token ?? null,
            refreshToken: parsed?.refresh_token ?? null,
          };
        }
      }
    }
  } catch {
    // Ignore storage read/parse errors
  }
  return { accessToken: null, refreshToken: null };
}

async function resolveAccessToken(): Promise<string | null> {
  let token: string | null = null;
  let expiresAt: number | null | undefined = undefined;

  try {
    const { data } = await supabase.auth.getSession();
    token = data.session?.access_token ?? null;
    expiresAt = data.session?.expires_at;
  } catch {
    // getSession may fail if offline or memory store not hydrated
  }

  // Fallback to localStorage if getSession didn't find the token
  let refreshToken: string | null = null;
  if (!token) {
    const stored = getLocalStoredTokens();
    token = stored.accessToken;
    refreshToken = stored.refreshToken;
  }

  const needsRefresh =
    !token ||
    isSessionExpiring(expiresAt) ||
    isJwtExpired(token);

  if (needsRefresh) {
    try {
      const refreshed = refreshToken
        ? await supabase.auth.refreshSession({ refresh_token: refreshToken })
        : await supabase.auth.refreshSession();
      if (refreshed.data.session?.access_token) {
        token = refreshed.data.session.access_token;
      }
    } catch {
      // Keep the existing token; the server will reject it if it is unusable.
    }
  }

  return token;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const token = await resolveAccessToken();

    return next({
      headers: token
        ? {
            Authorization: `Bearer ${token}`,
            [ACCESS_TOKEN_HEADER]: token,
          }
        : {},
    });
  },
);
